import type { Departure_station } from "@prisma/client";
import { inferRouterOutputs } from "@trpc/server";
import { type NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Pagination from "../components/Paginations";
import { filterStations } from "../helpers/sortArray";
import { AppRouter } from "../server/api/root";
import { api } from "../utils/api";

type RouterOutput = inferRouterOutputs<AppRouter>;

type StationsGetOutput = RouterOutput['stations']['getStations']

const Stations: NextPage = () => {
  const [stations, setStations] = useState<StationsGetOutput>([0, []]);
  const [search, setSearch] = useState("");
  const [pagination, setPagination] = useState<number>(0);

  const { data } = api.stations.getStations.useQuery({ skip: pagination });
  
  useEffect(() => {
    if (data) setStations(data);
  }, [data]);

  function handleSearchChange(e: React.ChangeEvent<HTMLInputElement>) {
    setSearch(e.target.value);
    if (!data) return;

    if(e.target.value === "") {
      setStations(data)
    } else {
      setStations([pagination, filterStations(data[1], e.target.value)]);
    }
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen items-center justify-center bg-slate-800">
        <h1 className="text-white text-4xl pt-4 mb-4 font-extrabold leading-none text-center">Stations</h1>
        <div className="flex flex-col">
            <label htmlFor="search" className="text-white text-center text-lg">Search stations</label>
            <input id="search" type="text" className="rounded px-2 py-1 w-2xl mx-auto" value={search} placeholder="Name, address, city" onChange={handleSearchChange}></input>
        </div>
        <div className="relative overflow-x-auto shadow-md max-w-2xl mx-auto my-4 rounded">
          <table className="w-full text-sm text-left text-gray-300">
            <thead className="uppercase bg-gray-400 text-gray-900">
              <tr>
                <th scope="col" className="p-4">Name</th>
                <th scope="col" className="p-4">address</th>
                <th scope="col" className="p-4">city</th>
              </tr>
            </thead>
            <tbody>
              {stations[1].slice(0,10).map(s => (
              <tr className="bg-gray-300 border-b hover:bg-gray-600 text-gray-900" key={s.id}>
                <td className="p-4">{s.name}</td>
                <td className="p-4">{s.address}</td>
                <td className="p-4">{s.city}</td>
              </tr>
              ))}
            </tbody>
          </table>
        </div>
        <Pagination maxItems={stations[0]} pagination={pagination} setPagination={setPagination} />
      </main>
    </>
  );
};

export default Stations;
